MiniPhyloTrees:
	g++ -std=c++17 -g -pthread -Wall -Wno-unused-function -Wno-unused-private-field -I/mnt/c/Users/abbys/boost/boost_1_61_0 -I../../Empirical/include/emp/ MiniPhyloTrees.cpp

TestingBoost: 
	g++ -std=c++17 -g -pthread -Wall -Wno-unused-function -Wno-unused-private-field -I/mnt/c/Users/abbys/boost/boost_1_61_0 -I../../Empirical/include/emp/ TestingBoost.cpp

NullModel: 
	g++ -std=c++17 -o NullModelExec -g -pthread -Wall -Wno-unused-function -Wno-unused-private-field -I/mnt/c/Users/abbys/boost/boost_1_61_0 -I../../Empirical/include/emp/ NullModel.cpp

PressureForDiversity: 
	g++ -std=c++17 -o PressureForDiversityExec -g -pthread -Wall -Wno-unused-function -Wno-unused-private-field -I/mnt/c/Users/abbys/boost/boost_1_61_0 -I../../Empirical/include/emp/ PressureForDiversity.cpp
