GenTrees:
	g++ -std=c++17 -g -pthread -Wall -Wno-unused-function -Wno-unused-private-field -I/mnt/c/Users/abbys/boost/boost_1_61_0 -I../../Empirical/include/emp/ GenTrees.cpp

DiversityTrees: 
	g++ -std=c++17 -g -pthread -Wall -Wno-unused-function -Wno-unused-private-field -I/mnt/c/Users/abbys/boost/boost_1_61_0 -I../../Empirical/include/emp/ DiversityTrees.cpp
