NormalizationPressureForDiversity: 
	g++ -std=c++17 -o NormalizationPressureForDiversityExec -g -pthread -Wall -Wno-unused-function -Wno-unused-private-field -I/mnt/c/Users/abbys/boost/boost_1_61_0 -I../../../Empirical/include/emp/ NormalizationPressureForDiversity.cpp
